DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_blog/', include(('my_blog.urls', 'my_blog'), namespace='my_blog')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),

    path('password_reset', include('password_reset.urls')),
]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('post_comment/<int:article_id>', views.post_comment, name='post_comment'),
    path('comment_delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('post_comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),
]

my_blog/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.index_handler, name='index'),
    path('article_list', views.article_list, name='article_list'),  # 博客列表

    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),  # 查看博客详情

    path('article_create/', views.article_create, name='article_create'),  # 创建博客

    path('article_revise/<int:id>/', views.article_revise, name='article_revise'),  # 修改博客
    # path('article_revise/<int:id>/', views.ArticleRevise.as_view(), name='article_revise'),  # 修改博客

    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),  # 删除博客

    path('column_create/', views.column_create, name='column_create'),   # 新建栏目

    # path('tag_create/<int:user_id>', views)

]

my_blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from PIL import Image


class ArticleColumn(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    # 统计浏览次数
    total_views = models.IntegerField(default=0)

    # 文章标题图
    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)

    columns = models.ForeignKey(
        to=ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        # 调用原有的 save() 方法
        article = super(ArticlePost, self).save()
        print(self.avatar)
        # 固定宽度缩放图片大小
        if self.avatar and not update_fields:   # update_fields排除article_detail中的浏览量增加，提升性能
            print('start')
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)

        return article


class ArticleTag(models.Model):
    title = models.CharField(max_length=100)
    # author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(to=ArticlePost, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

my_blog/forms.py
from django import forms
from .models import ArticlePost, ArticleColumn, ArticleTag
from django.forms import fields


class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body', 'columns', 'avatar',)
        # exclude = ('tags',)


class ColumnPostForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('title',)


class TagPostForm(forms.ModelForm):

    class Meta:
        model = ArticleTag
        fields = ('title', 'article',)

        # exclude = ('column', 'body',)

my_blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import decorators
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm
import markdown

from .forms import ArticlePostForm, ColumnPostForm
from .models import ArticlePost, ArticleColumn, ArticleTag


# Create your views here.
def index_handler(request):
    return HttpResponse('404 Not Found XD')


def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')

    # 用户搜索操作
    if search:
        articles = ArticlePost.objects.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search) |
            Q(author__username__icontains=search) |
            Q(columns__title__icontains=search)
        )

    else:
        # 如果用户没有搜索, search=None 传递到模板会被转换成 "None" 字符串
        search = ''
        # 如果有排序进行处理
        articles = ArticlePost.objects.all()

    if column:
        articles = articles.filter(columns=ArticleColumn.objects.get(title=column))

    if order == 'total_views':
        articles = articles.order_by('-total_views')
    else:
        order = ''

    # 传递给Paginator进行分页
    paginator = Paginator(articles, 6)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    # 传递每篇文章的标签
    for art in articles:
        art.tags = ArticleTag.objects.filter(article_id=art.id)

    context = dict(
        articles=articles,
        order=order,
        search=search,
    )
    # render函数：载入模板，并返回context对象
    return render(request, 'my_blog/list.html', context)


def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    print(article.avatar)

    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])  # update_fields表名只有total_views发生改变，提升性能

    # Markdown扩展
    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',  # 目录扩展
        ])

    # 筛选评论
    comments = Comment.objects.filter(article=id)
    article.body = md.convert(article.body)  # 处理文章正文
    article.tags = ArticleTag.objects.filter(article_id=id)

    comment_form = CommentForm()

    context = dict(
        article=article,
        toc=md.toc,
        comments=comments,
        comment_form=comment_form,
    )

    return render(request, 'article/detail.html', context)


@decorators.login_required(login_url='/userprofile/login/')
def article_create(request):
    if request.method == 'POST':
        article_post_form = ArticlePostForm(request.POST, request.FILES)  # 文件包含文章封面图
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = request.user  # 文章作者

            # 处理文章栏目
            if request.POST['column'] != 'none':
                new_article.columns = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()

            # 创建文章标签
            tags_new = request.POST['tags'].split(';')
            for t in tags_new:
                if t:
                    tag = ArticleTag(title=t, article=ArticlePost.objects.get(id=new_article.id))
                    tag.save()

            return redirect('my_blog:article_list')
        return HttpResponse("表单内容有误，请重新填写。")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()  # 获取所有栏目信息，供下拉栏显示
        context = dict(
            type='创建文章',
            title='',
            body='在此输入...',
            article_form=article_post_form,
            article_column='none',
            columns=columns,
            tags='',
        )
        # 返回模板
        return render(request, 'article/create.html', context)


@decorators.login_required(login_url='/userprofile/login/')
def article_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("my_blog:article_list")
    else:
        return HttpResponse("本次访问仅允许post请求")


@decorators.login_required(login_url='/userprofile/login/')
def article_revise(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            print(article_post_form.cleaned_data)
            article.title = article_post_form.cleaned_data['title']
            article.body = article_post_form.cleaned_data['body']
            # 修改文章封面图
            print(request.FILES)
            if 'avatar' in request.FILES:
                article.avatar = article_post_form.cleaned_data['avatar']
            # 修改文章栏目
            if request.POST['column'] != 'none':
                article.columns = ArticleColumn.objects.get(id=request.POST['column'])
            article.save()

            # 修改标签，剔除旧标签，增加新标签
            tags_old = list(map(lambda a: a.title, list(ArticleTag.objects.filter(article_id=id))))
            tags_new = request.POST['tags'].split(';')

            tags_delete = [t for t in tags_old if t not in tags_new]  # 应删除的标签
            tags_add = [t for t in tags_new if t not in tags_old]  # 应新增加的标签
            for t in tags_delete:
                ArticleTag.objects.get(article_id=id, title=t).delete()
            for t in tags_add:
                if t:
                    tag = ArticleTag(title=t, article=ArticlePost.objects.get(id=id))
                    tag.save()

            return redirect('my_blog:article_list')
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    else:
        article_revise_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = dict(
            type='修改文章',
            title=article.title,
            body=article.body,
            article_form=article_revise_form,
            article_column=article.columns,
            columns=columns,
            tags=';'.join(list(map(lambda a: a.title, list(ArticleTag.objects.filter(article_id=id))))),  # 所有标签字符串
        )
        return render(request, 'article/create.html', context)


def column_create(request):
    if request.method == 'POST':
        column_form = ColumnPostForm(data=request.POST)
        if column_form.is_valid():
            column_form.save()
            return redirect("my_blog:article_list")
        else:
            return HttpResponse("表单信息填写有误，请重新填写！")
    else:
        column_form = ColumnPostForm()
        context = dict(
            column_form=column_form,
        )
        return render(request, "article/createColumn.html", context)

templates/my_blog/list.html
{# extends表明此页面继承 base.html 文件 #}
{% extends "base.html" %}
{% load staticfiles %}

{# 写入 base.html 中定义的 title #}
{% block title %}
    首页
{% endblock title %}

{# 写入 base.html 定义的 content #}
{% block content %}

    <div class="container">

        {# 筛选 最新 / 最热 #}
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url "my_blog:article_list" %}?search={{ search }}">
                        最新
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url "my_blog:article_list" %}?order=total_views&search={{ search }}">
                        最热
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url "my_blog:article_list" %}">
                        返回首页
                    </a>
                </li>
            </ol>
        </nav>

        {# 搜索栏 #}
        <div class="row">
            <div class="col-auto mr-auto">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
                    <button type="submit" class="btn btn-primary">搜索</button>
                </form>
            </div>
        </div>

        {# 搜索提示语 #}
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下： </h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color:red">"{{ search }}"</span>有关的文章。 </h4>
            {% endif %}
        {% endif %}

        <div class="row mt-2">
            {% for article in articles %}
                <!-- 文章内容 -->
                <div class="col-12">

                    {# 标题图 #}
                    {% if article.avatar %}
                        <div class="col">
                            <img src="{{ article.avatar.url }}" alt="avatar"
                                 style="max-width: 100px; border-radius: 20px">
                        </div>
                    {% endif %}

                    {# 标题 #}
                    <h4>
                        <b>
                            <a href="{% url "my_blog:article_detail" article.id %}" style="color:black;">
                                {{ article.title }}
                            </a>
                        </b>
                    </h4>

                    {# 标签 #}
                    {% if article.tags %}
                        <span>
                            {% for tag in article.tags %}
                                <a href="#" class="badge badge-secondary">
                                    {{ tag }}
                                </a>
                            {% endfor %}
                        </span>
                    {% endif %}

                    {# 摘要 #}
                    <div>
                        <p style="color:grey;">
                            {{ article.body|slice:':100' }}...
                        </p>
                    </div>
                    {# 注脚 #}
                    <p>
                        <span style="color: #545b62;">
                            作者：{{ article.author }}&nbsp;&nbsp;
                        </span>
                        <span style="color:green;">
                            {{ article.total_views }} 浏览&nbsp;&nbsp;
                        </span>
                        <span style="color:blue;">
                            {{ article.created|date:'Y-m-d' }} 发布&nbsp;&nbsp;
                        </span>
                        <span style="color:darkred;">
                            {{ article.updated|date:'Y-m-d' }} 更新&nbsp;&nbsp;
                        </span>

                        {# 栏目 #}
                        <span>
                            {% if article.columns.title %}
                                <a href="?column={{ article.columns.title }}&order={{ order }}&search={{ search }}">
                                    <button class="btn btn-sm mb-2" type="button">
                                        {{ article.columns.title }}
                                    </button>
                                </a>
                            {% endif %}
                        </span>

                    </p>
                    <hr>
                </div>
                {#                <hr style="width: 100%;"/>#}
            {% endfor %}
        </div>
        <a href="{% url 'my_blog:article_create' %}" class="btn btn-info">新建文章</a>

        {# 显示页码 #}
        <div class="pagination row">
            <div class="m-auto">
            <span class="step-links">

                {# 如果不是第一页，则显示上翻按钮 #}
                {% if articles.has_previous %}
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-info">上一页</a>


                    <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-primary">
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}


                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                {# 如果不是最后一页，显示下翻按钮 #}
                {% if articles.has_next %}

                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-primary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}"
                       class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-info">
                    下一页
                    </a>
                {% endif %}
            </span>
            </div>
        </div>
    </div>

    <script>
        function Color() {
            this.r = Math.floor(Math.random() * 255);
            this.g = Math.floor(Math.random() * 255);
            this.b = Math.floor(Math.random() * 255);
            this.color = 'rgba(' + this.r + ',' + this.g + ',' + this.b + ',0.8)';
        }
    </script>


{% endblock content %}

templates/my_blog/oldList.html
{# extends表明此页面继承 base.html 文件 #}
{% extends "base.html" %}
{% load staticfiles %}

{# 写入 base.html 中定义的 title #}
{% block title %}
    首页
{% endblock title %}

{# 写入 base.html 定义的 content #}
{% block content %}

    <div class="container">

        {# 筛选 最新 / 最热 #}
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url "my_blog:article_list" %}?search={{ search }}">
                        最新
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url "my_blog:article_list" %}?order=total_views&search={{ search }}">
                        最热
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url "my_blog:article_list" %}">
                        返回首页
                    </a>
                </li>
            </ol>
        </nav>

        {# 搜索栏 #}
        <div class="row">
            <div class="col-auto mr-auto">
                <form class="form-inline">
                    <label class="sr-only">content</label>
                    <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
                    <button type="submit" class="btn btn-primary">搜索</button>
                </form>
            </div>
        </div>

        {# 搜索提示语 #}
        {% if search %}
            {% if articles %}
                <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下： </h4>
                <hr>
            {% else %}
                <h4>暂无<span style="color:red">"{{ search }}"</span>有关的文章。 </h4>
            {% endif %}
        {% endif %}

        <div class="row mt-2">
            {% for article in articles %}
                <!-- 文章内容 -->
                <div class="col-4 mb-4">
                    <!-- 卡片容器 -->
                    <div class="card h-100">
                        <!-- 标题 -->
                        <a href="{% url "my_blog:article_detail" article.id %}">
                            <h4 class="card-header">{{ article.title }}</h4>
                        </a>

                        <div class="card-body">
                            <h5 class="card-columns">Author: {{ article.author }}</h5>
                        </div>

                        <!-- 摘要 -->
                        <div class="card-body">
                            <p class="card-text">{{ article.body|slice:'100' }}...</p>
                        </div>
                        <!-- 注脚 -->
                        <div class="card-footer">
                            <a href="{% url 'my_blog:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a href="{% url 'my_blog:article_create' %}" class="btn btn-info">新建文章</a>

        {# 显示页码 #}
        <div class="pagination row">
            <div class="m-auto">
            <span class="step-links">

                {# 如果不是第一页，则显示上翻按钮 #}
                {% if articles.has_previous %}
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-info">上一页</a>


                    <a href="?page=1&&order={{ order }}&search={{ search }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-primary">
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}


                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                {# 如果不是最后一页，显示下翻按钮 #}
                {% if articles.has_next %}

                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-primary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}"
                       class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}"
                       class="btn btn-info">
                    下一页
                    </a>
                {% endif %}
            </span>
            </div>
        </div>
    </div>


{% endblock content %}