DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_blog/', include(('my_blog.urls', 'my_blog'), namespace='my_blog')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),

    path('password_reset', include('password_reset.urls')),
]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('post_comment/<int:article_id>', views.post_comment, name='post_comment'),
    path('comment_delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('post_comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),
]

userprofile/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('delete/<int:id>', views.user_delete, name='delete'),
    path('edit/<int:id>', views.profile_edit, name='edit'),
    path('register/', views.user_register, name='register'),
    path('edit_password/<int:id>', views.edit_password, name='edit_password'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    # 与 User 模型构成一对一关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone = models.CharField(max_length=20, blank=True, null=True)
    # 头像
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True, null=True)
    # 个人简介
    bio = models.TextField(max_length=500, blank=True, null=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)


# # 信号接收函数，每当新建 User 实例时自动调用
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     print()
#     if created:
#         Profile.objects.create(user=instance)
#
#
# # 信号接收函数，每当更新 User 实例时自动调用
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

userprofile/forms.py
# 引入表单类
from django import forms
# 引入 User 模型
from django.contrib.auth.models import User
from .models import Profile


# 登录表单，继承了forms.Form类
class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio',)


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=16)
    password2 = forms.CharField(max_length=16)

    class Meta:
        model = User
        fields = ('username', 'email')

    def check_password(self):
        data = self.cleaned_data
        if data['password1'] == data['password2']:
            return data['password1']
        else:
            raise forms.ValidationError("密码不一致，请重新输入！")

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse

from .forms import UserLoginForm, ProfileForm, UserRegisterForm
from .models import Profile


def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # cleaned_data 清洗出合法数据
            profile = user_login_form.cleaned_data
            # authenticate 检验账号、密码是否正确匹配数据库,匹配则返回这个user对象
            user = authenticate(username=profile['username'], password=profile['password'])
            if user:
                # 将用户数据保存在session中，即实现了登录动作
                login(request, user)
                return redirect("my_blog:article_list")
            else:
                return HttpResponse("账号或密码输入有误，请重新输入！")

        else:
            return HttpResponse("账号或密码输入不合法")

    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = dict(
            form=user_login_form,
        )
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


def user_logout(request):
    logout(request)
    return redirect("my_blog:article_list")


@login_required(login_url='/user/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        # 验证登录用户与待删除用户是否相同
        if request.user == user:
            # 退出登录
            logout(request)
            user.delete()
            return redirect('my_blog:article_list')
        else:
            return HttpResponse("抱歉！您没有删除操作的权限。")
    else:
        return HttpResponse("仅接受POST请求。")


@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    if Profile.objects.filter(user_id=user.id):
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)

    if request.method == 'POST':
        if request.user != user:
            return HttpResponse('你没有权限修改此用户的信息。')

        profile_form = ProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():

            profile.phone = profile_form.cleaned_data['phone']
            profile.bio = profile_form.cleaned_data['bio']

            # 如果 request.FILES 存在文件，则保存
            if 'avatar' in request.FILES:
                profile.avatar = profile_form.cleaned_data['avatar']
            profile.save()
            # 带参数的 重定向
            return redirect("my_blog:article_list")
        else:
            return HttpResponse("注册表单输入有误，请重新输入。")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = dict(
            profile_form=profile_form,
            profile=profile,
            user=user
        )
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse('请使用GET或POST请求数据')


def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password1'])
            new_user.save()
            login(request, new_user)
            return redirect("my_blog:article_list")
        else:
            return HttpResponse("注册表单有误，请重新输入！")

    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = dict(
            form=user_register_form,
        )
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")


@login_required(login_url='/userprofile/login')
def edit_password(request, id):
    user = User.objects.get(id=id)
    if request.method == 'POST':
        if not user.check_password(request.POST['password1']):
            user.set_password(request.POST['password1'])
            user.save()
            logout(request)
            return redirect("my_blog:article_list")
        else:
            return HttpResponse("密码不能与之前的相同！")

    elif request.method == 'GET':
        return render(request, 'userprofile/edit_password.html')
    else:
        return HttpResponse("请使用GET或POST请求数据")

templates/userprofile/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <div class="col-md-4">
                    用户名：{{ user.username }}  <a href="{% url "userprofile:edit_password" user.id %}" class="navbar-dark">修改密码</a>
                </div>
                <br>

                {# 头像显示 #}
                {% if profile.avatar %}
                    <div class="col-md-4">头像</div>
                    <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4" height=100 width=100>
                {% else %}
                    <h5 class="col-md-4">暂无头像</h5>
                {% endif %}
                <br>
                <br>


                <form method="post" action="{% url "userprofile:edit" profile.user.id %}" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="avatar">上传头像</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                    <div class="form-group col-md-4">
                        <label for="phone">
                            电话
                        </label>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                    </div>

                    <div class="form-group col-md-4">
                        <label for="bio">
                            简介
                        </label>
                        <textarea type="text" class="form-control" id="bio" name="bio" rows="12"></textarea>
                        <script>
                            document.getElementById("bio").value = "{{ profile.bio }}"
                        </script>
                    </div>

                    <button type="submit" class="btn btn-primary">
                        提交
                    </button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

templates/userprofile/edit_password.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    登录
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="{% url "userprofile:edit_password" user.id %}">
                {% csrf_token %}

                {# 密码 #}
                <div class="form-group col-md-4">
                    <label for="password1">设置密码</label>
                    <input type="password" class="form-control" id="password1" name="password1" required>
                </div>

                {# 确认密码 #}
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>

                {# 提交按钮 #}
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} 登录 {% endblock title %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}

                    <div class="form-group">
                        <label for="username">账号</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>

                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>

                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
                <br>
                <h5>
                    <a href="{% url "password_reset_recover" %}">忘记密码了？</a>
                </h5>
                <h5>
                    <a href="{% url "userprofile:register" %}">注册</a>
                </h5>
            </div>
        </div>
    </div>

{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    登录
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}

                {# 账号 #}
                <div class="form-group col-md-4">
                    <label for="username">昵称</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>

                {# 邮箱 #}
                <div class="form-group col-md-4">
                    <label for="email">邮箱</label>
                    <input type="email" class="form-control" id="email" name="email">
                </div>

                {# 密码 #}
                <div class="form-group col-md-4">
                    <label for="password1">设置密码</label>
                    <input type="password" class="form-control" id="password1" name="password1" required>
                </div>

                {# 确认密码 #}
                <div class="form-group col-md-4">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>

                {# 提交按钮 #}
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}