DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_blog/', include(('my_blog.urls', 'my_blog'), namespace='my_blog')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),

    path('password_reset', include('password_reset.urls')),
]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('post_comment/<int:article_id>', views.post_comment, name='post_comment'),
    path('comment_delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('post_comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),
]

my_blog/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.index_handler, name='index'),
    path('article_list', views.article_list, name='article_list'),  # 博客列表

    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),  # 查看博客详情

    path('article_create/', views.article_create, name='article_create'),  # 创建博客

    path('article_revise/<int:id>/', views.article_revise, name='article_revise'),  # 修改博客
    # path('article_revise/<int:id>/', views.ArticleRevise.as_view(), name='article_revise'),  # 修改博客

    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),  # 删除博客

    path('column_create/', views.column_create, name='column_create'),   # 新建栏目

    # path('tag_create/<int:user_id>', views)

]

userprofile/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('delete/<int:id>', views.user_delete, name='delete'),
    path('edit/<int:id>', views.profile_edit, name='edit'),
    path('register/', views.user_register, name='register'),
    path('edit_password/<int:id>', views.edit_password, name='edit_password'),
]

templates/base.html
<!-- 载入静态文件 -->
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    {# 预留网站标题 #}
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>
<body>
    {% include 'header.html' %}
    {# 预留具体页面的位置 #}
    {% block content %}{% endblock content %}
    {# 引入注脚 #}
    {% include 'footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    {% block script %}{% endblock script %}
</body>
</html>

templates/footer.html
{% load staticfiles %}

<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">

    <div class="container">

        <p class="m-0 text-center text-white">Copyright &copy; www.cygao.top 2020</p>

    </div>

</footer>

templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="{% url "my_blog:article_list" %}">我的博客</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <!-- 条目 -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_blog:article_list' %}">文章</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_blog:article_create' %}">来写一篇吧</a>
                </li>

                {% if user.is_authenticated %}

                    {# 如果用户已经登录，则显示用户名下拉框 #}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'userprofile:logout' %}">退出登录</a>

                            <a class="dropdown-item" href="{% url 'userprofile:edit' user.id %}">修改信息</a>

                            <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                        </div>
                    </li>

                {% else %}
                    {# 如果未登录，则显示“登录” #}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
                    </li>

                {% endif %}

            </ul>
        </div>

    </div>
</nav>

{% if user.is_authenticated %}
    <form
            style="display:none;"
            id="user_delete"
            action="{% url "userprofile:delete" user.id %}"
            method="post"
    >
        {% csrf_token %}
        <button type="submit">发送</button>
    </form>
    <script>
        function user_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除用户资料吗？",
                yes: function (index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}

{# ... #}

{#{% if user.is_authenticated %}#}
{##}
{#        <a type="submit">发送</a>#}
{#        </form>#}
{#        <script>#}
{#            function comment_delete() {#}
{#                layer.open({#}
{#                    title: "确认删除",#}
{#                    content: "确认删除此评论吗？",#}
{#                    yes: function (index, layero) {#}
{#                        $('form#comment_delete button').click();#}
{#                        layer.close(index)#}
{#                    },#}
{#                })#}
{#            }#}
{#        </script>#}
{##}
{#    {% endif %}#}