DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_blog/', include(('my_blog.urls', 'my_blog'), namespace='my_blog')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),

    path('password_reset', include('password_reset.urls')),
]

urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('post_comment/<int:article_id>', views.post_comment, name='post_comment'),
    path('comment_delete/<int:comment_id>', views.comment_delete, name='comment_delete'),
    path('post_comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply'),
]

my_blog/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.index_handler, name='index'),
    path('article_list', views.article_list, name='article_list'),  # 博客列表

    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),  # 查看博客详情

    path('article_create/', views.article_create, name='article_create'),  # 创建博客

    path('article_revise/<int:id>/', views.article_revise, name='article_revise'),  # 修改博客
    # path('article_revise/<int:id>/', views.ArticleRevise.as_view(), name='article_revise'),  # 修改博客

    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),  # 删除博客

    path('column_create/', views.column_create, name='column_create'),   # 新建栏目

    # path('tag_create/<int:user_id>', views)

]

userprofile/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('delete/<int:id>', views.user_delete, name='delete'),
    path('edit/<int:id>', views.profile_edit, name='edit'),
    path('register/', views.user_register, name='register'),
    path('edit_password/<int:id>', views.edit_password, name='edit_password'),
]

templates/article/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}{{ type }}{% endblock title %}

{% block content %}
    {# 写文章表单 #}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}

                    {# 文章标题 #}
                    <div class="form-group">
                        <label for="title">文章标题：</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ title }}">
                    </div>

                    {# 文章标题 #}
                    <div class="form-group">
                        <label for="avatar">标题图片</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>

                    {# 选择栏目 #}
                    <div class="form-group">
                        <label for="columns">选择栏目</label>&nbsp;&nbsp;&nbsp;&nbsp;

                        {# 新建栏目 #}
                        <button type="button" href="{% url "my_blog:column_create" %}" class="btn btn-success"
                                onclick="location.href='{% url "my_blog:column_create" %}'">新建栏目
                        </button>

                        <select class="form-control" id="columns" name="column">

                            <option value="none">无</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}"
                                    {% if article_column.id == column.id %}
                                        selected="selected"
                                    {% endif %}>
                                    {{ column }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>

                    {# 文章标签 #}
                    <div class="form-group">
                        <label for="tags">标签</label>
                        <input type="text" class="form-control col-3" id="tags" name="tags" value="{{ tags }}">
                    </div>

                    {# 文章正文 #}
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        {# 文本区域 #}
                        <textarea type="text" class="form-control" id="body" name="body"
                                  rows="12">{{ body }}</textarea>
                    </div>
                    {# 提交按钮 #}
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

templates/article/createColumn.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}创建栏目{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}

                    {# 栏目名称 #}
                    <div class="form-group">
                        <label for="title">栏目名称</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>

                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    文章详情
{% endblock title %}

{% block content %}

    <div class="container">
        <div class="row">
            {# 标题及作者 #}
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>

            {# 标签 #}
            {% if article.tags %}
                <p>
                    {% for tag in article.tags %}
                        <a href="#" class="badge badge-secondary">
                            {{ tag }}
                        </a>
                    {% endfor %}
                </p>
            {% endif %}

            <div class="col-12 alert alert-success">作者：{{ article.author }}

                {% if user.id == article.author.id %}
                    {# 判断登录用户是否是作者 #}

                    <a href="#" onclick="confirm_delete()">删除文章</a>
                    {# 新增一个隐藏的表单 #}
                    <form
                            style="display: none;"
                            id="safe_delete"
                            action="{% url 'my_blog:article_delete' article.id %}"
                            method="post">
                        {% csrf_token %}
                        <button type="submit">发送？？？</button>
                    </form>

                    <a href={% url "my_blog:article_revise" article.id %}>修改文章</a>

                {% endif %}

                <div>
                    浏览数：{{ article.total_views }}
                </div>
            </div>

            <div class="col-12">
                {# 管道符 | 是Django过滤器的写法，|safe表示该HTML不需要进行转义了 #}
                <p>{{ article.body|safe }}</p>
            </div>
            <hr>

            {# 评论框 #}
            {% if user.is_authenticated %}
                <div>
                    <form action="{% url "comment:post_comment" article.id %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>说点什么吧：</strong>
                            </label>
                            <div>
                                {{ comment_form.media }}
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">发送</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    请<a href="{% url "userprofile:login" %}">登录</a>后回复
                </h5>
                <br>
            {% endif %}

            {# 显示评论 #}
            <br>
            {% load mptt_tags %}
            <h4>共有{{ comments.count }}条评论</h4>
            <div class="row">
                <!-- 遍历树形结构 -->
                {% recursetree comments %}
                    <!-- 给 node 取个别名 comment -->
                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                        offset-1 col-11
                        {% else %}
                        col-12
                        {% endif %}"
                        >
                            <hr>
                            <p>
                                <strong style="color: pink">
                                    {{ comment.user }}
                                </strong>

                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right"
                                       style="color: cornflowerblue;"
                                    ></i>
                                    <strong style="color: pink">
                                        {{ comment.reply_to }}
                                    </strong>
                                {% endif %}

                            </p>
                            <div>{{ comment.body|safe }}</div>

                            <div>
                    <span style="color: gray">
                        {{ comment.created|date:"Y-m-d H:i" }}
                    </span>

                                <!-- 加载 modal 的按钮 -->
                                {% if user.is_authenticated %}
                                    <button type="button"
                                            class="btn btn-light btn-sm text-muted"
                                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                    >
                                        回复
                                    </button>
                                {% else %}
                                    <a class="btn btn-light btn-sm text-muted"
                                       href="{% url 'userprofile:login' %}"
                                    >
                                        回复
                                    </a>
                                {% endif %}
                            </div>

                            <!-- Modal -->
                            <div class="modal fade"
                                 id="comment_{{ comment.id }}"
                                 tabindex="-1"
                                 role="dialog"
                                 aria-labelledby="CommentModalCenter"
                                 aria-hidden="true"
                            >
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height: 480px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">
                                                回复 {{ comment.user }}：</h5>
                                        </div>
                                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>


                    {% endwith %}
                {% endrecursetree %}
            </div>

            {#            <div>#}
            {#                {% for comment in comments %}#}
            {#                    <hr>#}
            {#                    <p>#}
            {#                        <strong style="color:pink">#}
            {#                            {{ comment.user }}#}
            {#                        </strong> 于#}
            {#                        <span style="color:green">#}
            {#                            {{ comment.created|date:"Y-m-d H:i:s" }}#}
            {#                        </span> 时说：#}
            {##}
            {# 删除评论 #}
            {#                        {% if user.id == comment.user.id %}#}
            {#                            <a href="#" onclick="comment_delete()">删除</a>#}
            {##}
            {#                            <form#}
            {#                                    style="display: none"#}
            {#                                    id="comment_delete"#}
            {#                                    action="{% url "comment:comment_delete" comment.id %}"#}
            {#                                    method="post">#}
            {#                                {% csrf_token %}#}
            {#                                <button type="submit">发送？？？</button>#}
            {#                            </form>#}
            {#                        {% endif %}#}
            {##}
            {#                    </p>#}
            {#                    <pre style="font-family: inherit;font-size: 1em;">{{ comment.body }}</pre>#}
            {#                {% endfor %}#}
            {#            </div>#}

            <br>

            {# 目录 #}
            {#            <div class="col-3 mt-4">#}
            {#                <h4><strong>目录</strong></h4>#}
            {#                <hr>#}

            {#                <div>#}
            {#                    {{ toc|safe }}#}
            {#                </div>#}
            {#            </div>#}
        </div>
    </div>

    <script>

        function load_modal(article_id, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;

            // 加载编辑器
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/comment/post_comment/' +
                    article_id +
                    '/' +
                    comment_id +
                    '"' +
                    ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                    comment_id +
                    '"></iframe>';
                $(modal_body).append(content);
            }
            ;

            $(modal_id).modal('show');
        }

        function confirm_delete() {
            // 调用layer弹窗组件
            layer.open({
                title: "确认删除",
                content: "确认删除这篇文章吗?",
                yes: function (index, layero) {
                    // 指定前往的 url
                    $('form#safe_delete button').click();
                    layer.close(index);
                    // 旧版本
                    {#location.href = '{% url "my_blog:article_delete" article.id %}'#}
                }
            })
        }

        function comment_delete() {
            layer.open({
                title: "确认删除",
                content: "确认该评论吗？",
                yes: function (index, layero) {
                    $('form#comment_delete button').click();
                    layer.close(index);
                }
            })
        }
    </script>

    {% block script %}
        <script>
            $(".django-ckeditor-widget").removeAttr('style');
        </script>
    {% endblock script %}

{% endblock content %}